### ISSUE TITLE
Does it actually function? 

### ISSUE THREAD

**Issue by 01GOD** [fredtesche/xxx-303#1]
Is that sort of a pseudocode electronics description?

**Comment by fredtesche** [comment]
Code is written in Arduino language, which is related to C++.

Haven't touched this for quite a while, but the internal sequencer does actually function... Mostly! It's possible to hardcode triggers/notes in the arrays in globals.h, and play MIDI data over USB.

The sequencer hardware is sitting on the shelf collecting dust. I'll pick this project up again at some point.
